package model.enums;

public enum MessageType {
    SIGN_UP,
    NEW_SQUAD,
    SHOW_SQUADS,
    JOIN_SQUAD,
    REQUEST_TO_ADMIN,
    LEAVE_SQUAD,
    SQUAD_DATA,
    SERVER_CONNECTION,
    REMOVE_MEMBER,
    PAY_TO_VAULT,
    INIT,
    START_BATTLE,
    DISCONNECTION,
    BATTLE_REQUEST,
    ANSWER_TO_BATTLE_REQUEST,
    START_GAME,
    CHANGE_STATE,
}
